const products = [
  {
    id: 1,
    category: "GRP",
    name: "GRP2602(W)",
    price: "185.00 QR",
    desc: "2-Line Essential IP Phone Designed for Mass Deployment and Easy Management The GRP2602 features 5-way voice conferencing to maximize productivity, integrated PoE (GRP2602P/GRP2602G), Wi-Fi support (GRP2602W), and is supported by Grandstream’s Device Management System (GDMS). ",
    images: [
      "./src/img/GRP2602(PWG)/grp2602_front_web.webp",
      "./src/img/GRP2602(PWG)/grp2602_left_web.webp",
      "./src/img/GRP2602(PWG)/grp2602_side_web.webp",
      "./src/img/GRP2602(PWG)/GRP2602_back.webp",
    ],
    list: [
      "Supports 2 lines, and 4 SIP accounts.",
      "Supported by GDMS which provides a centralized interface to configure, provision, manage and monitor Grandstream devices",
      "Electronic Hook Switch (EHS) support for Plantronics, Jabra, and Sennheiser headsets Full-duplex speakerphone with HD audio to maximize audio quality and clarity.",
      "Equipped with noise shield technology and AI noise reduction to minimize background noise",
      "The GRP2602P/GRP2602G includes built-in PoE to power the device and give it a network connection",
      "Supports 5-way audio conferencing for easy conference calls",
      "Enterprise-level protection including secure boot, dual firmware images, and encrypted data storage",
      "Swappable faceplate to allow for easy logo customization",
      "GRP2602W includes integrated dual-band (2.4GHz and 5GHz) Wi-Fi 6 (802.11a/b/g/n/ac/ax) - hardware version 5.0 and above",
    ],
    youtube: "https://www.youtube.com/embed/woQrHZZzYwU",
    pdf: "./src/img/GRP2602(PWG)/Datasheet_GRP2602_English.pdf",
  },
  {
    id: 2,
    category: "GRP",
    name: "GRP2602(P)",
    price: "140.00 QR",
    desc: "2-Line Essential IP Phone Designed for Mass Deployment and Easy Management The GRP2602 features 5-way voice conferencing to maximize productivity, integrated PoE (GRP2602P/GRP2602G), Wi-Fi support (GRP2602W), and is supported by Grandstream’s Device Management System (GDMS). ",
    images: [
      "./src/img/GRP2602(PWG)/grp2602_front_web.webp",
      "./src/img/GRP2602(PWG)/grp2602_left_web.webp",
      "./src/img/GRP2602(PWG)/grp2602_side_web.webp",
      "./src/img/GRP2602(PWG)/GRP2602_back.webp",
    ],
    list: [
      "Supports 2 lines, and 4 SIP accounts.",
      "Supported by GDMS which provides a centralized interface to configure, provision, manage and monitor Grandstream devices",
      "Electronic Hook Switch (EHS) support for Plantronics, Jabra, and Sennheiser headsets Full-duplex speakerphone with HD audio to maximize audio quality and clarity.",
      "Equipped with noise shield technology and AI noise reduction to minimize background noise",
      "The GRP2602P/GRP2602G includes built-in PoE to power the device and give it a network connection",
      "Supports 5-way audio conferencing for easy conference calls",
      "Enterprise-level protection including secure boot, dual firmware images, and encrypted data storage",
      "Swappable faceplate to allow for easy logo customization",
      "GRP2602W includes integrated dual-band (2.4GHz and 5GHz) Wi-Fi 6 (802.11a/b/g/n/ac/ax) - hardware version 5.0 and above",
    ],
    youtube: "https://www.youtube.com/embed/woQrHZZzYwU",
    pdf: "./src/img/GRP2602(PWG)/Datasheet_GRP2602_English.pdf",
  },
  {
    id: 3,
    category: "GRP",
    name: "GRP2602(G)",
    price: "160.00 QR",
    desc: "2-Line Essential IP Phone Designed for Mass Deployment and Easy Management The GRP2602 features 5-way voice conferencing to maximize productivity, integrated PoE (GRP2602P/GRP2602G), Wi-Fi support (GRP2602W), and is supported by Grandstream’s Device Management System (GDMS). ",
    images: [
      "./src/img/GRP2602(PWG)/grp2602_front_web.webp",
      "./src/img/GRP2602(PWG)/grp2602_left_web.webp",
      "./src/img/GRP2602(PWG)/grp2602_side_web.webp",
      "./src/img/GRP2602(PWG)/GRP2602_back.webp",
    ],
    list: [
      "Supports 2 lines, and 4 SIP accounts.",
      "Supported by GDMS which provides a centralized interface to configure, provision, manage and monitor Grandstream devices",
      "Electronic Hook Switch (EHS) support for Plantronics, Jabra, and Sennheiser headsets Full-duplex speakerphone with HD audio to maximize audio quality and clarity.",
      "Equipped with noise shield technology and AI noise reduction to minimize background noise",
      "The GRP2602P/GRP2602G includes built-in PoE to power the device and give it a network connection",
      "Supports 5-way audio conferencing for easy conference calls",
      "Enterprise-level protection including secure boot, dual firmware images, and encrypted data storage",
      "Swappable faceplate to allow for easy logo customization",
      "GRP2602W includes integrated dual-band (2.4GHz and 5GHz) Wi-Fi 6 (802.11a/b/g/n/ac/ax) - hardware version 5.0 and above",
    ],
    youtube: "https://www.youtube.com/embed/woQrHZZzYwU",
    pdf: "./src/img/GRP2602(PWG)/Datasheet_GRP2602_English.pdf",
  },

  {
    id: 4,
    category: "WIFI",
    name: "WP810",
    price: "315.00 QR",
    desc: "Basic Cordless Wi-Fi IP Phone with Integrated Dual-Band 802.11a/b/g/n/ac  and 6-hour talk time The WP810 includes advanced antenna design and roaming support. By adding 6-hour talk time and HD voice with dual-MICs, the WP810 offers an affordable option and comes equipped with a combination of features, mobility and durability to suit all portable telephony needs.",
    images: [
      "./src/img/WP810/WP810-1.webp",
      "./src/img/WP810/wp810_front_web.webp",
      "./src/img/WP810/wp810_left_web.webp",
      "./src/img/WP810/wp810_back_cradle_web.webp",
      "./src/img/WP810/WP810_back_clip.webp",
    ],
    list: [
      "Dual-band Wi-Fi with efficient antenna design and advanced roaming support",
      "2 SIP accounts, 2 lines",
      "HD voice & dual MIC design with AEC and Noise Shield Technology",
      "Rechargeable 1500mAh battery, 6 hour talk time, 120-hour standby",
      "Configurable button for push-to-talk",
      "Micro USB port and 3.5mm headset jack",
    ],
    youtube: "https://www.youtube.com/embed/LAAqGRNidDo",
    pdf: "./src/img/WP810/Datasheet_WP810_English.pdf",
  },
  {
    id: 5,
    category: "GXP",
    name: "GXP1625",
    price: "130.00 QR",
    desc: "A standard Basic IP desktop phone to keep workers in-touch and productive. The GXP1620/25 features effective and essential functionalities to create an easy-to-use experience for a user with light to medium call volume. Its focus on essential features and standard call support makes the GXP1620/25 a versatile and dependable phone.",
    images: [
      "./src/img/GXP1625/gxp1620_25_front_web.webp",
      "./src/img/GXP1625/gxp1620_25_side_web.webp",
      "./src/img/GXP1625/gxp1620_25_right_web.webp",
      "./src/img/GXP1625/gxp1620_25_left_web.webp",
    ],
    list: [
      "2 SIP accounts, 2 line keys, 3-way conferencing, 3 XML programmable context-sensitive soft keys",
      "Dual-switched 10/100 mbps ports, integrated PoE on GXP1625",
      "HD audio on speakerphone and handset",
      "EHS support for Plantronics headsets",
      "Up to 1000 contacts, call history up to 200 records",
    ],
    youtube: "",
    pdf: "./src/img/GXP1625/datasheet_gxp1620_1625_english.pdf",
  },
  {
    id: 6,
    category: "GXP",
    name: "GXP1615",
    price: "120.00 QR",
    desc: "A simple IP phone for small business users, the GXP1610/GXP1610P/1615 delivers a user-friendly VoIP calling experience in a very easy-to-use IP phone. The GXP1610/ GXP1610P/1615 offers support for 1 line, 2 call appearances and includes 3-way voice conferencing to maximize productivity. Additional features include a 132x48 (2.95’’.) LCD screen for easy viewing, 3 XML programmable soft keys for customization, 10/100 mbps ports, integrated PoE on the GXP1610P/GXP1615 model, EHS support for Plantronics headsets and multi-language support. These features allow the GXP1610/GXP1610P/GXP1615 to be a high-quality small business IP phone that is simple and easy-to-use.",
    images: [
      "./src/img/GXP1615/gxp1610_15_front_web.webp",
      "./src/img/GXP1615/gxp1610_15_side_web.webp",
      "./src/img/GXP1615/gxp1610_15_right_web.webp",
      "./src/img/GXP1615/gxp1610_15_left_web.webp",
    ],
    list: [
      "1 SIP account, up to 2 call appearances",
      "TLS and SRTP security encryption technology to protect calls and accounts",
      "3-way audio conferencing for easy conference calls",
      "Electronic Hook Switch (EHS) support for Plantronics headsets",
      "Automated provisioning options include TR-069 and XML config files",
      "Full-duplex speakerphone with HD audio to maximize audio quality and clarity",
      "Use with Grandstream’s UCM series of IP PBXs for Zero Config provisioning",
      "Built-in PoE 802.3af to power the device and give it a network connection (GXP1610P/PGXP1615 ony)",
    ],
    youtube: "",
    pdf: "./src/img/GXP1615/datasheet_gxp1610_1615_english.pdf",
  },
  {
    id: 7,
    category: "GXP",
    name: "GXP1628",
    price: "195.00 QR",
    desc: "The GXP1628 brings an efficient call environment to any desktop. This phone delivers a an easy-to-use interface and simple design with its 132x48 backlit LCD screen, 2-line/SIP account keys and 8 dual-color LCD BLF/speed-dial keys.<br>Also equipped with dual Gigabit ports with integrated PoE, the GXP1628 is built for a variety of deployment scenarios.<br>Added customization and usability comes with its built in HD audio and 3 XML programmable soft keys. As all Grandstream IP phones do, the GXP1628 features state-of-the-art security encryption technology (SRTP and TLS).<br>The GXP1628 supports a variety of automated provisioning options, including zero-configuration with Grandstream’s UCM series IP PBXs, encrypted XML files and TR-069, to make mass deployment extremely easy.",
    images: [
      "./src/img/GXP1628/gxp1628_front.webp",
      "./src/img/GXP1628/gxp1628_side.webp",
      "./src/img/GXP1628/gxp1628_right-1.webp",
      "./src/img/GXP1628/gxp1628_left.webp",
    ],
    list: [
      "2 SIP accounts, 2 line keys, 3-way conferencing, 3 XML programmable context-sensitive soft keys",
      "Dual-switched Gigabit ports, integrated PoE",
      "HD audio on speakerphone and handset",
      "8 dual-colored BLF/speed dial keys",
      "EHS support for Plantronics headsets",
      "Up to 1000 contacts, call history up to 200 records",
    ],
    youtube: "",
    pdf: "./src/img/GXP1628/datasheet_gxp1628_english.pdf",
  },
  {
    id: 8,
    category: "WIFI",
    name: "WP820",
    price: "470.00 QR",
    desc: "Cordless Wi-Fi IP Phone with Integrated Dual-Band 802.11a/b/g/n  and 7.5-hour talk time The WP820 includes advanced antenna design and roaming support. By adding 7.5-hour talk time and HD voice with dual-MICs, the WP820 offers an affordable option and comes equipped with a combination of features, mobility and durability to suit all portable telephony needs.",
    images: [
      "./src/img/WP820/wp820_right_front_cradle_web.webp",
      "./src/img/WP820/wp820_front_web.webp",
      "./src/img/WP820/wp820_back_web.webp",
    ],
    list: [
      "Dual-band WiFi with efficient antenna design and advanced roaming support",
      "Bluetooth for syncing headsets and mobile devices (contacts and call transferring)",
      "HD voice & dual MIC design with AEC and Noise Shield Technology",
      "Rechargeable 1500mAh battery, 7.5 hour talk time, 150-hour standby",
      "Accelerometer and configurable button for push-to-talk, panic and other related functions",
      "Micro USB port and 3.5mm headset jack",
      "2 SIP accounts, 2 lines",
      "Supports custom Android apps that fit the phone’s screen/keys",
      "Battery charger (GMC08) that can charge up to 8 batteries at a time is available separately",
    ],
    youtube: "",
    pdf: "./src/img/WP820/datasheet_wp820_english.pdf",
  },
  {
    id: 9,
    category: "GRP",
    name: "GRP2604(P)",
    price: "225.00 QR",
    desc: "3-Line Essential IP Phone Designed for Mass Deployment and Easy Management The GRP2604 features 5-way voice conferencing to maximize productivity, integrated PoE (GRP2604P) and is supported by Grandstream’s Device Management System (GDMS). ",
    images: [
      "./src/img/GRP2604P/grp2604_front_web.webp",
      "./src/img/GRP2604P/grp2604_left_web.webp",
      "./src/img/GRP2604P/grp2604_side_web.webp",
      "./src/img/GRP2604P/grp2604_back_web.webp",
    ],
    list: [
      "3 lines, 6 SIP accounts, up to 3 call appearances",
      "Supported by GDMS which provides a centralized interface to configure, provision, manage and monitor Grandstream devices",
      "Electronic Hook Switch (EHS) support for Plantronics, Jabra, and Sennheiser headsets",
      "Full-duplex speakerphone with HD audio to maximize audio quality and clarity",
      "Equipped with noise shield technology and AI noise reduction to minimize background noise",
      "Dual switched autosensing 10/100/1000 Mbps Gigabit Ethernet ports with integrated PoE (GRP2604P only)",
      "Supports 5-way audio conferencing for easy conference calls",
      "Enterprise-level protection including secure boot, dual firmware images, and encrypted data storage",
      "Swappable faceplate to allow for easy logo customization",
    ],
    youtube: "https://www.youtube.com/embed/woQrHZZzYwU",
    pdf: "./src/img/GRP2604P/Datasheet_GRP2604_English.pdf",
  },
  {
    id: 10,
    category: "GXP",
    name: "GXP2160",
    price: "435.00 QR",
    desc: "The GXP2160 provides an efficiency-focused endpoint with its vibrant display and intuitive BLF and speed-dial keys. Focus on handling more calls and reaching more customers by utilizing its 6 lines, 4.3” LCD screen and built-on physical 24 BLF/speed-dial keys. Easily monitor presence and status of other extensions to quickly transfer calls to the right destination. Equipped with dual Gigabit, PoE network ports, Bluetooth support, and a host of other features the GXP2160 brings call control to a new level.<br><br>As all Grandstream IP phones do, the GXP2160 features state-of-the-art security encryption technology (SRTP and TLS). The GXP2160 supports a variety of automated provisioning options, including zero-configuration with Grandstream’s UCM series IP PBXs, encrypted XML files and TR-069, to make mass deployment extremely easy.",
    images: [
      "./src/img/GXP2160/gxp2160left.png",
      "./src/img/GXP2160/gxp2160front.webp",
      "./src/img/GXP2160/gxp2160right.webp",
      "./src/img/GXP2160/gxp2160Side.webp",
    ],
    list: [
      "Supports 6 lines, 6 SIP accounts and 5-way voice conferencing",
      "4.3 inch (480x272) color-screen LCD",
      "Dual Gigabit ports, integrated PoE",
      "HD audio on speakerphone and handset, 5 programmable context-sensitive soft keys",
      "24 dual-colored BLF/speed dial keys",
      "Integrated Bluetooth",
    ],
    youtube: "",
    pdf: "./src/img/GXP2160/datasheet_gxp2160_english.pdf",
  },
  {
    id: 11,
    category: "GRP",
    name: "GRP2670",
    price: "585.00 QR",
    desc: "12-Line Professional IP Phone Designed for Mass Deployment and Easy Management <br>The GRP2670 features 48 virtual multi-purpose keys (VPKs), integrated Wi-Fi, Bluetooth support, a 7-inch touchscreen and more, and is supported by Grandstream’s Device Management System (GDMS).",
    images: [
      "./src/img/GRP2670/GRP2670_frontv2.webp",
      "./src/img/GRP2670/GRP2670_leftv2.webp",
      "./src/img/GRP2670/GRP2670_side.png",
      "./src/img/GRP2670/GRP2670_back.webp",
    ],
    list: [
      "12 lines, 16 SIP accounts",
      "Supported by GDMS which provides a centralized interface to configure, provision, manage and monitor Grandstream devices",
      "7-inch (1024x600) capacitive touch screen",
      "Full-duplex speakerphone with HD audio to maximize audio quality and clarity",
      "Equipped with noise shield technology to minimize background noise",
      "Dual switched autosensing 10/100/1000 Mbps Gigabit Ethernet ports with integrated PoE",
      "Integrated Bluetooth support",
      "Enterprise-level security protection including secure boot, dual firmware images, and encrypted data storage",
      "Integrated dual-band (2.4GHz and 5GHz) Wi-Fi 6 (802.11a/b/g/n/ac/ax) - hardware version 5.0 and above",
    ],
    youtube: "",
    pdf: "./src/img/GRP2670/Datasheet_GRP2670_English.pdf",
  },
  {
    id: 12,
    category: "GRP",
    name: "GRP2615(W)",
    price: "495.00 QR",
    desc: "10-Line Professional IP Phone Designed for Mass Deployment and Easy Management<br>The GRP2615 features 40 multi-purpose keys (MPKs),  integrated Wi-Fi, Bluetooth support, a color LCD with swappable face plates for easy logo customization and more and is supported by Grandstream’s Device Management System (GDMS). ",
    images: [
      "./src/img/GRP2615W/GRP2615-front.webp",
      "./src/img/GRP2615W/GRP2615_ext_multiple.webp",
      "./src/img/GRP2615W/GRP2615_right.webp",
      "./src/img/GRP2615W/GRP2615_ext_front.webp",
    ],
    list: [
      "HD audio, handset and speakerphone with support for wide-band audio",
      "10 line keys with up to 16 SIP accounts",
      "40 built-in digital BLF keys; available extension module offers 40 BLF/speed dial keys per module",
      "Enterprise-level protection including secure boot, dual firmware images, and encrypted data storage",
      "integrated dual-band Wi-Fi 802.11 a/b/g/n/ac (2.4Ghz & 5Ghz)",
      "Dual switched auto-sensing 10/100/1000 Mbps Gigabit Ethernet ports with integrated PoE",
      "Swappable face plates to allow for easy logo customization",
      "Integrated Bluetooth",
    ],
    youtube: "",
    pdf: "./src/img/GRP2615W/Datasheet_GRP2615_English.pdf",
  },
  {
    id: 13,
    category: "GRP",
    name: "GRP2613",
    price: "240.00 QR",
    desc: "6-Line Professional IP Phone Designed for Mass Deployment and Easy Management<br>The GRP2613(W) features 24 virtual multi-purpose keys (VPKs), integrated Wi-Fi 6 (GRP2613W), dual Gigabit ports, a color LCD with swappable face plates for easy logo customization, and more. It is supported by Grandstream’s Device Management System (GDMS).",
    images: [
      "./src/img/GRP2613/grp2613_front_web.webp",
      "./src/img/GRP2613/grp2613_left_web.webp",
    ],
    list: [
      "Supports 4 (GRP2613) or 6 (GRP2613W) SIP accounts and 6 multipurpose line keys",
      "Swappable face plates to allow for easy logo customization",
      "Dual switched autosensing 10/100/1000 Mbps Gigabit ethernet ports with integrated PoE",
      "Equipped with noise shield technology to minimize background noise",
      "HD audio with support for all major codecs, including wideband codecs G.722 and Opus",
      "Up to 24 digital BLF keys",
      "Integrated dual-band  (2.4GHz and 5GHz) Wi-Fi 6 (802.11a/b/g/n/ac/ax) and  Bluetooth® (GRP2613W only)",
      "Enterprise-level protection including secure boot, dual firmware images, and encrypted data storage",
    ],
    youtube: "",
    pdf: "./src/img/GRP2613/Datasheet_GRP2613(W)_English.pdf",
  },
  {
    id: 14,
    category: "GRP",
    name: "GRP2636",
    price: "470.00 QR",
    desc: "12-Line Professional IP Phone Designed for Mass Deployment and Easy Management<br>The GRP2624 features 24 multi-purpose (MPK) extension keys with paper slot, integrated Wi-Fi and POE, a 4.3-inch LCD color LCD and more, and is supported by Grandstream’s Device Management System (GDMS).",
    images: [
      "./src/img/GRP2636/GRP2636 2.webp",
      "./src/img/GRP2636/GRP2636 3.webp",
      "./src/img/GRP2636/GRP2636 6.webp",
      "./src/img/GRP2636/GRP2636 7.webp",
    ],
    list: [
      "12 lines, 16 SIP accounts",
      "Supported by GDMS which provides a centralized interface to configure, provision, manage and monitor Grandstream devices",
      "RJ9 headset jack allowing EHS with Plantronics headsets, and integrated USB Headset support",
      "Full-duplex speakerphone with HD audio to maximize audio quality and clarity",
      "Equipped with noise shield technology to minimize background noise",
      "Dual switched autosensing 10/100/1000 Mbps Gigabit Ethernet ports with integrated PoE",
      "Supports 5-way audio conferencing for easy conference calls",
      "Enterprise-level protection including secure boot, dual firmware images, and encrypted data storage",
      "Swappable faceplate to allow for easy logo customization data storage",
      "Integrated dual-band (2.4GHz and 5GHz) Wi-Fi 6 (802.11a/b/g/n/ac/ax) - hardware version 5.0 and above",
    ],
    youtube: "",
    pdf: "./src/img/GRP2636/Datasheet_GRP2636_English.pdf",
  },
  {
    id: 15,
    category: "GRP",
    name: "GRP2616",
    price: "530.00 QR",
    desc: "6-Line Professional IP Phone Designed for Mass Deployment and Easy Management<br>The GRP2616 features 48 virutal multi-purpose keys (VPKs),  integrated Wi-Fi, Bluetooth support, a 4.3 inch color LCD with swappable face plates for easy logo customization, additional 2.4 inch display screen, and is supported by Grandstream’s Device Management System (GDMS). ",
    images: [
      "./src/img/GRP2616/GRP2616.webp",
      "./src/img/GRP2616/GRP2616left.webp",
      "./src/img/GRP2616/GRP2616right.webp",
      "./src/img/GRP2616/GRP2616side.webp",
    ],
    list: [
      "HD audio, handset and speakerphone with support for wide-band audio",
      "6 line keys with up to 16 SIP accounts",
      "Dual LCD screens with digital BLF Keys",
      "Enterprise-level protection including secure boot, dual firmware images, and encrypted data storage",
      "Integrated dual-band 802.11 a/b/g/n/ac Wi-Fi",
      "Dual switched auto-sensing 10/100/1000 Mbps Gigabit Ethernet ports with integrated PoE",
      "Swappable face plates to allow for easy logo customization",
      "Integrated Bluetooth",
    ],
    youtube: "",
    pdf: "./src/img/GRP2616/Datasheet_GRP2616_English.pdf",
  },
  {
    id: 16,
    category: "GXP",
    name: "GXP2140",
    price: "380.00 QR",
    desc: "The customizable GXP2140 brings a rich and vibrant display, and call control to the medium to high-volume call user. This device provides the perfect balance for the call-intensive user’s desktop, with its 4 lines, 5 programmable soft keys and feature-loaded call controls. Its 4.3” color LCD display creates a high-quality user experience, and its dual Gigabit PoE ports, HD audio, and integrated Bluetooth makes the GXP2140 highly versatile as well.<br><br>As all Grandstream IP phones do, the GXP2140 features state-of-the-art security encryption technology (SRTP and TLS). The GXP2140 supports a variety of automated provisioning options, including zero-configuration with Grandstream’s UCM series IP PBXs, encrypted XML files and TR-069, to make mass deployment extremely easy.",
    images: [
      "./src/img/GXP2140/gxp2140_front.webp",
      "./src/img/GXP2140/gxp2140left.webp",
      "./src/img/GXP2140/gxp2140right.webp",
      "./src/img/GXP2140/gxp2140side.webp",
    ],
    list: [
      "Supports 4 lines, 4 SIP accounts and 5-way voice conferencing",
      "HD audio on speakerphone and handset, 5 programmable context-sensitive soft keys",
      "Compatible with GXP2200 LCD extension module (GXP2200 EXT)",
      "4.3 inch (480x272) color-screen LCD",
      "Dual Gigabit ports, integrated PoE",
      "Integrated Bluetooth for use with Bluetooth headsets and Bluetooth-enabled mobile devices (transferring contact books and calls), USB, EHS for Plantronics headsets",
    ],
    youtube: "",
    pdf: "./src/img/GXP2140/datasheet_gxp2140_english.pdf",
  },
  {
    id: 17,
    category: "GXP",
    name: "GXP2170",
    price: "435.00 QR",
    desc: "The GXP2170 is a powerful High-End IP phone that is ideal for busy users who handle high call volumes. Receptionists, administrators, sales staff and other call-intensive rolls  can enjoy efficiency by utilizing the GXP2170’s 12 line keys, 4.3 inch color display LCD and 48 digital, on-screen speed dial/BLF keys. Provide users with the fastest possible connection speeds thanks to the device’s dual Gigabit, PoE network ports. Maximized call control, expandable speed dial/BLF capabilities and a sleek design makes this phone the ultimate high-volume experience.<br><br>As all Grandstream IP phones do, the GXP2170 features state-of-the-art security encryption technology (SRTP and TLS). The GXP2170 supports a variety of automated provisioning options, including zero-configuration with Grandstream’s UCM series IP PBXs, encrypted XML files and TR-069, to make mass deployment extremely easy.",
    images: [
      "./src/img/GXP2170/gxp2170_front_web.webp",
      "./src/img/GXP2170/gxp2170_left_web.webp",
      "./src/img/GXP2170/gxp2170_right_ext_web.webp",
      "./src/img/GXP2170/gxp2170_side_web.webp",
    ],
    list: [
      "12 lines, 6 SIP accounts, 5 soft keys and 5-way voice conferencing",
      "48 on-screen digitally customizable BLF/speed-dial keys",
      "4.3 inch (480x272) color-screen LCD",
      "Dual Gigabit ports, integrated PoE",
      "Integrated Bluetooth",
      "Supports up to four GXP2200EXT Modules for BLF/speed-dial access to up to 160 contacts",
    ],
    youtube: "",
    pdf: "./src/img/GXP2170/datasheet_gxp2170_english.pdf",
  },
  {
    id: 18,
    category: "GAC",
    name: "GAC2570(WORLD)",
    price: "1950.00 QR",
    desc: "The GAC2570 is a full-duplex conferencing device featuring high-quality voice communication for meeting rooms, huddle areas, boardrooms, and more.",
    images: [
      "./src/img/GAC2570/gac2570 2 website.webp",
      "./src/img/GAC2570/gac2570 zoom certified banner.webp",
      "./src/img/GAC2570/gac2570 4 website.webp",
      "./src/img/GAC2570/gac2570 5 website.webp",
    ],
    list: [
      "Full-duplex speakerphone with HD acoustic chamber, advanced acoustic echo cancellation, and microphone beamforming array",
      "12 omnidirectional microphones with MMAD (Multichannel Microphone Array Design)",
      "Supports 5m pickup range, and can be paired with two GMD1208 desktop wireless microphones up to 20m away for full-room coverage",
      "10/100/1000Mbps network port with PoE+ and dedicated media port for collaborate",
      "Integrated Bluetooth 5.0 support",
      "Integrated Wi-Fi 6, Dual-band 2.4 & 5GHz with 802.11 a/b/g/n/ac/ax",
      "Supports 12-party conferences",
    ],
    youtube: "",
    pdf: "./src/img/GAC2570/Datasheet_GAC2570_English.pdf",
  },
  {
    id: 19,
    category: "GXV",
    name: "GXV3370",
    price: "710.00 QR",
    desc: "Integrated Video Communications Solution<br>The GXV3370 IP Video Phone for Android combines a 16-line IP video phone with a multi-platform video collaboration solution and the functionality of an Android tablet to offer an all-in-one communications solution. ",
    images: [
      "./src/img/GXV3370/gxv3370_front.webp",
      "./src/img/GXV3370/gxv3370_right.webp",
      "./src/img/GXV3370/gxv3370_side_web.webp",
      "./src/img/GXV3370/gxv3370_video_left.webp",
    ],
    list: [
      "16 lines with up to 16 SIP accounts",
      "Built-in mega-pixel camera for video calling with privacy shutter",
      "Runs on Android 7.0 operating system",
      "Built-in Bluetooth for syncing with mobile devices and connecting Bluetooth headset",
      "Dual-switched auto-sensing 10/100/1000Mbps network ports",
      "Integrated dual-band Wi-Fi (2.4GHz & 5GHz)",
      "Built-in PoE/PoE+ to power the device and give it a network connection",
      "Speakerphone with HD acoustic chamber, advanced echo cancellation & excellent double-talk performance",
      "4-core 1.3GHz ARM Cortex A53 processor with 2GB RAM and 8GB eMMC Flash",
      "7’’ (1024×600) capacitive 5-point touch screen TFT LCD",
      "TLS and SRTP security encryption technology to protect calls and accounts",
      "7-way audio conferencing & 3-way 720p 30fps HD video conferencing capability",
    ],
    youtube: "",
    pdf: "./src/img/GXV3370/datasheet_gxv3370_english.pdf",
  },
  {
    id: 20,
    category: "GXV",
    name: "GXV3470",
    price: "1050.00 QR",
    desc: "Integrated Video Communications Solution<br>The GXV3470 IP Video Phone for Android combines a 16-line IP video phone with a multi-platform video collaboration solution and the functionality of an Android tablet to offer an all-in-one communications solution. ",
    images: [
      "./src/img/GXV3470/GXV3470-2.webp",
      "./src/img/GXV3470/GXV3470-3.webp",
      "./src/img/GXV3470/GXV3470-4.webp",
      "./src/img/GXV3470/GXV3470-7.webp",
    ],
    list: [
      "16 lines with up to 16 SIP accounts",
      "Built-in 2 mega-pixel CMOS camera for video calling with privacy shutter",
      "Runs on the Android 14 operating system",
      "Built-in Bluetooth 5.0 for syncing with mobile devices and connecting Bluetooth headsets",
      "Dual-switched auto-sensing 10/100/1000Mbps network ports",
      "Integrated dual-band Wi-Fi 6 (2.4GHz & 5GHz)",
      "Built-in PoE/PoE+ for power and network connections",
      "Dual-mic HD speakerphone with noise shield 2.0, advanced echo cancellation & excellent double-talk performance",
      "Quad-core 2.0GHz ARMCortex-A55 processor with 4GB RAM and 16GB eMMC Flash",
      "7’’ (800x1280) capacitive 5-point touch screen IPS LCD",
      "Peripherals include HDMI-out, USB, RJ9 headset with EHS",
      "10-way audio conferencing & 3-way 720p 30fps HD video conferencing capability",
    ],
    youtube: "",
    pdf: "./src/img/GXV3470/Datasheet_GXV3470_English.pdf",
  },
  {
    id: 21,
    category: "GRP",
    name: "GRP2612(P)",
    price: "170.00 QR",
    desc: "4-Line Professional IP Phone Designed for Mass Deployment and Easy Management<br>The GRP2612 features features Wi-Fi support on the GRP2612W and PoE on the GRP2612P/GRP2612W/GRP2612G and is supported by Grandstream’s Device Management System (GDMS). ",
    images: [
      "./src/img/GRP2612P/grp2612_front_web.webp",
      "./src/img/GRP2612P/grp2612_left_web.webp",
    ],
    list: [
      "Supports 4 SIP accounts and 4 multi-purpose line keys",
      "GRP2612W includes built-in dual-band Wi-Fi support",
      "Swappable faceplate to allow for easy logo customization",
      "HD audio supporting all major codecs, including wideband codecs G.722 and Opus",
      "Up to 16 digital BLF Keys",
      "Enterprise-level protection including secure boot, dual firmware images, and encrypted data storage",
      "Dual switched auto-sensing 10/100 Mbps Ethernet ports (GRP2612)",
      "Dual switched auto-sensing 10/100 Mbps Ethernet ports with integrated PoE (GRP2612P & GRP2612W)",
      "Dual switched auto-sensing 10/100/1000 Mbps Gigabit Ethernet ports with integrated PoE (GRP2612G)",
    ],
    youtube: "",
    pdf: "./src/img/GRP2612P/datasheet_grp2612_english.pdf",
  },
];

export default products;
